version: 2

project_name: hermod

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    binary: hermod
    ldflags:
      - -s -w
      - -X github.com/Faizan2005/DFS-Go/cmd.version={{.Version}}
      - -X github.com/Faizan2005/DFS-Go/cmd.commit={{.ShortCommit}}
      - -X github.com/Faizan2005/DFS-Go/cmd.date={{.Date}}

archives:
  - formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: "hermod_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - INSTALL.txt
      - USAGE.txt
      - LICENSE

checksum:
  name_template: "checksums.txt"

brews:
  - repository:
      owner: MFZNK05
      name: homebrew-hermod
    homepage: "https://github.com/MFZNK05/DFS-Go"
    description: "Hermod – P2P File Sharing for Campus Networks"
    license: "MIT"
    install: |
      bin.install "hermod"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
